AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: interview-mentorship-backend

Parameters:
  FFmpegLayerS3Bucket:
    Type: String
    Description: S3 bucket containing the FFmpeg layer ZIP file
    Default: ""
  FFmpegLayerS3Key:
    Type: String
    Description: S3 key for the FFmpeg layer ZIP file
    Default: "layers/ffmpeg-layer.zip"

Conditions:
  HasFFmpegLayer: !Not [!Equals [!Ref FFmpegLayerS3Bucket, ""]]

Globals:
  Function:
    Timeout: 10
    MemorySize: 128
    Tracing: Active
  Api:
    TracingEnabled: true
    Cors:
      AllowMethods: "'POST,GET,OPTIONS'"
      AllowHeaders: "'content-type'"
      AllowOrigin: "'*'"

Resources:
  # Layer personalizado do FFmpeg
  FFmpegLayer:
    Type: AWS::Lambda::LayerVersion
    Condition: HasFFmpegLayer
    Properties:
      LayerName: !Sub "${AWS::StackName}-ffmpeg-layer"
      Description: "FFmpeg binaries for video processing"
      Content:
        S3Bucket: !Ref FFmpegLayerS3Bucket
        S3Key: !Ref FFmpegLayerS3Key
      CompatibleRuntimes:
        - python3.9
        - python3.8

  ConvertVideoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/statesmachine/convert_video/
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 60
      MemorySize: 2240
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref RecordsTable
        - S3CrudPolicy:
            BucketName: !Sub "${AWS::AccountId}-${AWS::Region}-${AWS::StackName}-media"
      Environment:
        Variables:
          TABLE_NAME: !Ref RecordsTable
          INDEX_NAME: !Ref RecordsTableSecondaryIndex
          BUCKET: !Sub "${AWS::AccountId}-${AWS::Region}-${AWS::StackName}-media"
      Layers: !If
        - HasFFmpegLayer
        - [!Ref FFmpegLayer]
        - []

  # Resto do template permanece igual...
  RecordsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::AccountId}-${AWS::Region}-${AWS::StackName}-records"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: user
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: !Ref RecordsTableSecondaryIndex
          KeySchema:
            - AttributeName: user
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  RecordsTableSecondaryIndex:
    Type: String
    Default: user_index

Outputs:
  FFmpegLayerArn:
    Condition: HasFFmpegLayer
    Description: "ARN of the custom FFmpeg layer"
    Value: !Ref FFmpegLayer
    Export:
      Name: !Sub "${AWS::StackName}-FFmpegLayerArn"
